### ISSUE TITLE
Having issue when running the build script

### ISSUE THREAD

**Issue by kartoffelmozart** [DiabloRun/DiabloInterface#124]
When i run the build.bat it starts the building process, but I get an error:

Error: System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---

shortly after the line "Downloading and installing Roslyn".

I would really like to be able to build this, because i do not have a very good understanding on how to read process memory from a running process, and i was hoping i could edit the code of DiabloInterface, fool around, and build to see if i can figure out what all of the code does. Can anyone help me so i can run the build script properly?

**Comment by Zutatensuppe** [comment]
please check this section https://github.com/DiabloRun/DiabloInterface#troubleshooting-dev

**Comment by kartoffelmozart** [comment]
That helped a bit, thank you! But now there is another error further down :) This time in the task package section. It says:
An error occurred when executing task 'Package'.
Error: System.ArgumentException: 1 is not a supported code page.
Did you also get this exception?

**Comment by Zutatensuppe** [comment]
No, I didn't get that error and unfortunately don't immediately see what it means :(
But as it is inside the Package task, this means that DI was actually built, but just unable to be put into a zip for some reason.

By searching on the internet I found that it is probably related to the actual zip creation
(source https://stackoverflow.com/a/47997411/392905)
The zip creation happens here https://github.com/DiabloRun/DiabloInterface/blob/master/build.cake#L76

Could you change the top of the build.cake file to look like this and then try again?
```
#tool nuget:?package=vswhere
#addin nuget:?package=Cake.Compression&version=0.1.1
#addin nuget:?package=SharpZipLib&version=0.86.0

ICSharpCode.SharpZipLib.Zip.ZipConstants.DefaultCodePage = 437;
```
If that works I can add it to the build script, but as it is working for me without that line, I cannot verify if that is a valid fix.


Apart from that, what you can always try is building directly through Visual Studio instead of with the script, that should usually work all the times, you just wont have a zip bundle at the end. So for just testing stuff out or building your personal version of DI it could be a workaround for now.

**Comment by kartoffelmozart** [comment]
The extra line works! Thank you! :)

**Comment by Zutatensuppe** [comment]
Thanks for verifying! =)
